#
x-superset-image: &superset-image apache/superset:latest
x-superset-depends-on: &superset-depends-on
  - redis
x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 6G

  superset:
    env_file: docker/.env
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8000:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 256M

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

volumes:
  superset_home:
    external: false
  redis:
    external: false
